feat: allow to customize the Storage disk to use
swisnl/openapi-spec-generator pull request #6
Opened 2023-01-31 07:53 UTC by nelson6e65

Add `openapi.filesystem_disk` config key and use it as storage disk to put the generated file.

New key in config:

```php
return [
    /**
     * The storage disk to be used to place the generated `*_openapi.json` or `*_openapi.yaml` file.
     *
     * For example, if you use 'public' you can access the generated file as public web asset (after run `php artisan storage:link`).
     *
     * Supported: 'local', 'public' and (probably) any disk available in your filesystems (https://laravel.com/docs/9.x/filesystem#configuration).
     */
    'filesystem_disk' => env('OPEN_API_SPEC_GENERATOR_FILESYSTEM_DISK', 'local'),
];
```

2023-02-04 15:35 UTC, nelson6e65 commented
@bbrala @rolfvandekrol @Rocksheep @florisl is still active this project? 🥺

2023-02-06 12:46 UTC, JaZo commented
Hi @nelson6e65, thanks for your PR! Although it doesn't get a lot of attention, this project is certainly still active. We're actually thinking about ways to improve it and e.g. add support for custom filters. I'll review this PR ASAP, sorry for the delay!

2023-02-06 15:53 UTC, JaZo requested changes
Looks good! I just have some minor comments.

2023-02-06 15:53 UTC, JaZo commented on config/config.php
> +    'filesystem_disk' => env('OPEN_API_SPEC_GENERATOR_FILESYSTEM_DISK', 'local'),
Currently we use the default disk and although we assume it is 'local', it doesn't necessarily have to be that disk. By forcing the disk to be 'local' we break that functionality. A default of `null` would be better as that will result in the current behaviour; the default disk. We can then explain this behaviour in de doc above.
```suggestion
    'filesystem_disk' => env('OPEN_API_SPEC_GENERATOR_FILESYSTEM_DISK', null),
```

2023-02-06 15:53 UTC, JaZo commented on src/Commands/GenerateCommand.php
> +        // $fileUrl = $storageDisk->url($fileName);
Please remove this unused line.

2023-02-06 15:53 UTC, JaZo commented on tests/Feature/GenerateTest.php
> +        config(['openapi.filesystem_disk' => $disk]);
For as far as I'm concerned we can assume all storage drivers just work - we only create a file, nothing fancy - so we don't need to test different storage drivers. That means the data provider can be removed.

2023-02-06 17:58 UTC, JaZo approved these changes

2023-02-06 17:59 UTC, merged

2023-02-06 19:52 UTC, JaZo commented
Good to hear, we're open to more improvements!